### ISSUE TITLE
Installing on Raspbian Stretch (Raspberry Pi Zero)

### ISSUE THREAD

**Issue by RedKage** [gerbera/gerbera#218]
Hello people,

I'm like a noob when it comes to linux and I wish to install Gerbera on my Raspberry Pi Zero.

I tried to get the PPA Ubuntu build since I read a mention here in the issues that it should work.
I understood that my Pi requires an ARM build, and that the PPA builds do contain an ARM one.

So I went there https://launchpad.net/~stephenczetty/+archive/ubuntu/gerbera
and tried to execute `sudo add-apt-repository ppa:stephenczetty/gerbera`

Which failed as I do not even have the `add-apt-repository` binary.
So I installed that stuff with `sudo apt-get install software-properties-common`.

I re-ran `add-apt-repository ppa:stephenczetty/gerbera` and it now prints:
> aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/stretch

I take it that there is no 'compliant' ARM build for my system.
Does it means that have to build from source?

Thanks guys.

**Comment by elmodaddyb** [comment]
@RedKage - I think you might have to compile from source.  The Gerbera **ARM** build is popular and has been successful...it might be worth picking a common distro for ARM to build a package.

Would you say Raspbian is the most popular distro for ARM?

**Comment by RedKage** [comment]
Thanks, I will try to build it.

I cannot say if Raspbian is the most popular.
I do know it's the most inexpensive though and is super easy to set up (thanks to the n00bs distrib).
I bought a Raspbian mostly to have a small footprint server available from the outside of my LAN so I could WOL devices.
And then I thought, why not also have a small NAS-like thing in my LAN, which is why I got interested in Gerbera.

**Comment by RedKage** [comment]
Here we go, installing deps:
`sudo apt-get install libavutil-dev libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libavresample-dev libswscale-dev libswresample-dev libpostproc-dev`

> Package libmysqlclient-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or is only available from another source
> E: Package 'libmysqlclient-dev' has no installation candidate

However... doing `sudo apt-get install default-libmysqlclient-dev` does work for Stretch, I saw this on the interwebz.

Next... I skipped the install from taglib (1.11.x), and libupnp (1.8.x) from source because I'm lazy and I don't want to RTFM.

So I try to build directly
`git clone https://github.com/v00d00/gerbera.git`
`mkdir build`
`cd build`
`cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_LASTFM=1`
> cmake not found

So I do `sudo apt-get install cmake`
And re-run `cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_LASTFM=1`

Indeed I skipped installing libupnp so I got a nice
> gerbera requires libupnp 1.8.3 or above.

Which means I do have to install this guy as the RTFM explained.
So I do `sh ../gerbera/scripts/install-pupnp18.sh` to install this guy.
> autoconf not found

So install this guy too `sudo apt-get install autoconf`
And do `sh ../gerbera/scripts/install-pupnp18.sh` again

> configure.ac:573: error: possibly undefined macro: AC_PROG_LIBTOOL
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> autoreconf: /usr/bin/autoconf failed with exit status: 1

Uhhhh I dunno what that means bro.
So I try to use the duktape script to see if this will yield the same error
`sh ../gerbera/scripts/install-duktape.sh`
... this one worked.

So I'll try to allow the 'm4_pattern_allow' thingy to make pupnp18.sh work.
BRB

**Comment by RedKage** [comment]
Dude, thanks [guy](https://github.com/sanger-pathogens/gubbins/issues/130#issuecomment-153668985), The 'm4_pattern_allow' error means I had to install libtool.
So I did  `sudo apt-get install libtool` and indeed the whole script goes further....

Until  this
> gcc -DHAVE_CONFIG_H -I. -I../.. -I../../upnp/inc  -I../../upnp/inc -I../../ixml/inc -I./common/ -I./tvctrlpt   -pthread -g -O2 -Os -Wall -MT common/tv_ctrlpt-sample_util.o -MD -MP -MF common/.deps/tv_ctrlpt-sample_util.Tpo -c -o common/tv_ctrlpt-sample_util.o `test -f 'common/sample_util.c' || echo './'`common/sample_util.c
In file included from ../../upnp/inc/upnp.h:402:0,
                 from common/sample_util.h:49,
                 from common/sample_util.c:42:
../../upnp/inc/FileInfo.h:22:2: error: #error libupnp uses large file support, so users must do that, too
 #error libupnp uses large file support, so users must do that, too
  ^~~~~
Makefile:614: recipe for target 'common/tv_ctrlpt-sample_util.o' failed

Gotta investigate this too now...
You see this is why I hate to compile anything on Linux. It never goes according to plan.

**Comment by RedKage** [comment]
Okay, so I went to the interwebz again, and foud how to disable this "large file support" for libupnp.
In order to do that, I changed the script `install-pupnp18.sh` and replace the last line with
`./bootstrap && ./configure $extraFlags --enable-ipv6 --enable-reuseaddr --disable-largefile && make && sudo make install`
--> I just added `--disable-largefile`

Now this does work. The script finishes although I have no idea what I just disabled. I'm trying to survive here. If, for some reasons, large file support is required, I saw some dudes using a work around somewhere. Has to do with adding a param to ./configure and setting explicit byte offset or something.

So now I can go back to the cmake command.
`cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_LASTFM=1`
> Taglib not found!

Now I need Taglib...  I forgot.
`sh ../gerbera/scripts/install-taglib111.sh`
Uuuuhhh that one is slow.
Very slow. Around 1% per 20 secs... I'll be back in 30mins

**Comment by RedKage** [comment]
Alright taglib got built, but the cmake fails: now I require some FFMpeg lib.

I think I should have followed the FreeBSD part of the manual.
In the FreeBSD section in the doc there is the installation of libtools, and cmake and other stuff that I needed. So I guess I will use this doc to build better deps

**Comment by RedKage** [comment]
Pretty much, for Raspberry Pi Zero, people need to install the same stuff as for FreeBSD
`sudo apt-get install wget git autoconf automake libtool cmake gcc ffmpeg pkgconf`

Except that `taglib` `libav` `libexif` `liblastfm` `gmake` are not available from apt-get.
- taglib is covered thanks to the `install-taglib111.sh` script.
- lastfm is covered with the `install-lastfm.sh` script, but doesn't work without 'sudo' (/usr/bin/install: cannot create regular file '/usr/lib/liblastfmlib.so.1.3.0': Permission denied)
- Now are left `libav` `libexif` and `gmake`
- libav, might be solved with `sudo apt-get install libav-tools`

I tried to build with cmake again and got
> Could NOT find FFMpegThumbnailer (missing:  FFMPEGTHUMBNAILER_LIBRARIES FFMPEGTHUMBNAILER_INCLUDE_DIRS) 

Probably, the ffmpeg package is incomplete?

At this point, I'm will just remove this guy,
`cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=0 -DWITH_EXIF=1 -DWITH_LASTFM=1`

It worked.

**Comment by elmodaddyb** [comment]
@RedKage - Great job documenting the steps!! 👍 

We had previous issues with ARM based chips and large file offsets in memory allocation.  Without `LFS` ARM will likely compile and run just fine, but the streaming of bytes to your UPnP client may not succeed all the time.  Resulting in invalid byte headers sent from the server.

The memory allocation offset is different in ARM than in x86_64 or x386.  Large File Support solved this for us.

Check out this issue --> https://github.com/gerbera/gerbera/issues/105

As for the packages not being there... you could try to purge your `CMakeCache.txt` file in your `/build` directory when you are adding dependencies.  I usually clobber the `build` directory entirely after adding new deps. to make sure it looks up the packages again.

**Comment by RedKage** [comment]
Understood for the large file support: if I'm not too lazy I'll try to compile upnplib with it.
Everything else worked though, the make -j4 and the make install.

Now I need... to make it run :D
I see there is a web interface and a default config file was created.

Web UI works but I kinda need a user and pass.
Guess it's in the config ... 'gerbera' with 'gerbera'... makes sense... but doesn't do anything when I logging. Even with `accounts enabled="yes"` in the config.
Whelp, guess it's time to RTFM of mediatomb.

**Comment by RedKage** [comment]
Wait a second, the issue #105 is what I suffer from.
Muahahah login doesn't work for me because I did compile with no LFS.
That's just great.
Now I will have figure out a way to compile upnplib with LSF

**Comment by elmodaddyb** [comment]
You beat me to the post...was just about to say....#105 is UI login on ARM.  The LFS support has a few symptoms, noteably the UI login content size.

**Comment by RedKage** [comment]
So I managed to install pupnp with LFS.
To do so, I reverted the changes I previously made on `install-pupnp18.sh` and instead I added `CFLAGS='-D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64'` to the make comand

Rebuilt, and ran gerbera, now I can logging. Seems to work, I'll have to try all of this later.

**Comment by RedKage** [comment]
# Recap: How to compile on Raspbian Stertch #

## Get the sources ##
`git clone https://github.com/v00d00/gerbera.git`
`mkdir build`
`cd build`

## Build deps ##
- `sudo apt-get install wget git autoconf automake libtool cmake gcc ffmpeg pkgconf`
- `sudo apt-get install default-libmysqlclient-dev` as the

## Build more deps using the scripts provided in the source ##
- `sh ../gerbera/scripts/install-duktape.sh`
- `sh ../gerbera/scripts/install-taglib111.sh`
- `sudo sh ../gerbera/scripts/install-lastfm.sh` as without sudo it fails

## Build the pupnp lib ##
It requires editing the `install-pupnp18.sh` script
Change the last line with
`./bootstrap && ./configure $extraFlags --enable-ipv6 --enable-reuseaddr && make CFLAGS='-D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64' && sudo make install`
pretty much, you need to add the ` CFLAGS='-D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64'` part to the make command.

Now build this guy too with `sh ../gerbera/scripts/install-pupnp18.sh`

## Build and install gerbera ##
- `cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=0 -DWITH_EXIF=1 -DWITH_LASTFM=1`
- `make -j4`
- `sudo make install`

## Enjoy ##
Now what's left is to is to install FFMPEGTHUMBNAILER as I disabled this in the cmake command. There is still this to do.

**Comment by elmodaddyb** [comment]
@RedKage - This is awesome.  Perhaps we can enhance the scripts to accommodate ARM based.

Presently we use `uname` to determine whether we are linux, macOS, FreeBSD, etc.

What does Raspbian report for `uname`?  Anything unique?  We could use to alter the script options as you specified.

Thanks,
Eamonn

**Comment by RedKage** [comment]
I tried uname... it gives...
`Linux`
:p

Gotta find another way.

**Comment by elmodaddyb** [comment]
How about `uname -m`?

**Comment by RedKage** [comment]
uname -m
= `armv6l`

**Comment by v00d00** [comment]
@RedKage thanks for sticking with it.

The interesting part for me here is the LFS detection on Libupnp side, it doesn't look like it was working correctly.

IIRC it should have been fixed in https://github.com/mrjimenez/pupnp/pull/53 (i.e. you shouldnt have to override the cflags like that). I wonder if it is worth a report to them?

**Comment by RedKage** [comment]
Yeah the CFlags trick I used was from their [https://github.com/mrjimenez/pupnp/blob/master/ChangeLog](changelog)

Said trick should have been fixed since 1.8.3 I think.
I guess it could be worth to report it as not fixed for armv6l or something.
I have to say this is a bit over my head.

**Comment by peterlopen** [comment]
Hi, 

I tried to build gerbera on Raspbian GNU/Linux 8 (jessie), but there is a problem with pupnp build:

> make[3]: Entering directory '/home/pi/build/pupnp-release-1.8.3/upnp/sample'
> /bin/bash ../../libtool  --tag=CC   --mode=link gcc  -D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64   -o tv_ctrlpt common/tv_ctrlpt-sample_util.o common/tv_ctrlpt-tv_ctrlpt.o linux/tv_ctrlpt-tv_ctrlpt_main.o ../../upnp/libupnp.la ../../ixml/libixml.la 
> libtool: link: gcc -D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64 -o .libs/tv_ctrlpt common/tv_ctrlpt-sample_util.o common/tv_ctrlpt-tv_ctrlpt.o linux/tv_ctrlpt-tv_ctrlpt_main.o  ../../upnp/.libs/libupnp.so ../../ixml/.libs/libixml.so
> common/tv_ctrlpt-sample_util.o: In function `SampleUtil_Initialize':
> sample_util.c:(.text+0x28): undefined reference to `pthread_mutexattr_init'
> sample_util.c:(.text+0x38): undefined reference to `pthread_mutexattr_setkind_np'
> sample_util.c:(.text+0x54): undefined reference to `pthread_mutexattr_destroy'
> common/tv_ctrlpt-tv_ctrlpt.o: In function `TvCtrlPointStart':
> tv_ctrlpt.c:(.text+0x2324): undefined reference to `pthread_create'
> tv_ctrlpt.c:(.text+0x2330): undefined reference to `pthread_detach'
> linux/tv_ctrlpt-tv_ctrlpt_main.o: In function `main':
> tv_ctrlpt_main.c:(.text+0x58): undefined reference to `pthread_create'
> ../../upnp/.libs/libupnp.so: undefined reference to `pthread_rwlock_rdlock'
> ../../upnp/.libs/libupnp.so: undefined reference to `pthread_attr_setstacksize'
> ../../upnp/.libs/libupnp.so: undefined reference to `pthread_rwlock_init'
> ../../upnp/.libs/libupnp.so: undefined reference to `pthread_rwlock_destroy'
> ../../upnp/.libs/libupnp.so: undefined reference to `pthread_rwlock_wrlock'
> ../../upnp/.libs/libupnp.so: undefined reference to `pthread_rwlock_unlock'
> collect2: error: ld returned 1 exit status
> 

Looks like it is found by automake:

> --------------------------- pthread stuff -------------------------------------
> checking for the pthreads library -lpthreads... no
> checking whether pthreads work without any flags... no
> checking whether pthreads work with -Kthread... no
> checking whether pthreads work with -kthread... no
> checking for the pthreads library -llthread... no
> checking whether pthreads work with -pthread... yes
> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
> checking if more special flags are required for pthreads... no
> ----------------------- pthread_rwlock_t stuff --------------------------------
> checking if pthread_rwlock_t is available... yes, supported without any options
> 

looks somewhat similar to https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads, but I can not figure it out.

Please, any suggestion what is wrong?

Thank you.

regards,
peter

**Comment by philmoreau** [comment]
I had the same problem as @peterlopen ( _undefined reference to `pthread_*_). I was able to fix it by adding `LDFLAGS='-pthread -lpthread'` to to line 14 of "install-pupnp18.sh".

So the new line is :

`./bootstrap && ./configure $extraFlags --enable-ipv6 --enable-reuseaddr && make CFLAGS='-D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64' LDFLAGS='-pthread -lpthread' && sudo make install\`

**Comment by v00d00** [comment]
That is interesting, but should definitely not be necessary! You should probably report it to the libupnp guys upstream.

**Comment by edgar79** [comment]
Hello.
I was just reading through this issue because I'm interested in compiling gerbera on a regular Raspberry Pi 2 and RPi 3 (both running Raspbian Stretch).

@elmodaddyb : The `uname -m` test for the script on regular RPi 2 and RPi 3 give other results as on the Pi zero:

`$ uname -m`
armv7l
(not like on the RPi Zero: armv6l )

`$ cat /etc/os-release`
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

`dpkg --print-architecture`
armhf

**Comment by elmodaddyb** [comment]
Hello @edgar79 - We previously used the `uname -m` command to confirm that the system was truly running on **ARM** architecture.  This has a requirement that Large File Support be enabled, otherwise memory offsets are incorrect.

Have you tried following the steps to compile mentioned by @RedKage.  In one instance it requires some customization of the **pupnp** makefiles.

Let me know how far you've gotten with compilation?

**Comment by edgar79** [comment]
Hello @elmodaddyb - I successfully compiled and configured it using @RedKage s instructions. Also had to add the LDFLAGS @philmoreau mentioned.

But the install-scripts printed error messages:
`../gerbera/scripts/install-duktape.sh: 14: [: Linux: unexpected operator`
and
`../gerbera/scripts/install-taglib111.sh: 7: ../gerbera/scripts/install-taglib111.sh: [[: not found`
May be this is because of missing spaces between the brackets and the semicolons? (just guessing)

Thank you!

**Comment by v00d00** [comment]
I think we should report this LDFLAGs issue to pupnp, users that should not have to set those!

@edgar79 do you have a log of your pupnp build?

**Comment by edgar79** [comment]
Hello @v00d00 - these are the build logs with and without LDFLAGS set.

`../gerbera/scripts/install-pupnp18.sh >> logfile 2>&1 `

[install-pupnp18.sh.without-ldflags.log](https://github.com/gerbera/gerbera/files/1749661/install-pupnp18.sh.without-ldflags.log)
[install-pupnp18.sh.with-ldflags.log](https://github.com/gerbera/gerbera/files/1749662/install-pupnp18.sh.with-ldflags.log)

**Comment by gkzsolt** [comment]
Hi @edgar79, the [[ in the taglib install script is not an error, but you should use bash for it, not sh.
So I used:
`# bash ../gerbera/scripts/install-taglib111.sh`

**Comment by gkzsolt** [comment]
I am trying to compile gerbera for Debian Jessie. I could not install `libswresample-dev`, because it
`Depends: libavutil-dev (= 7:3.2.10-1~deb9u1~bpo8+1) but 6:11.12-1~deb8u1 is to be installed`.
What I'll lose by _not_ building with `LibAV/FFmpeg (-DWITH_AVCODEC=0)` ?

**Comment by gkzsolt** [comment]
Ok, I managed to install it from backports:

`# apt-get -t jessie-backports install libswresample-dev`

**Comment by elmodaddyb** [comment]
@gkzsolt the ffmpeg library is used for a few capabilities
* filling metadata about the video/audio files
* thumbnails for videos (along with ffmpeg-thumbnailer)
* AVI fourcc transcoding support

**Comment by gkzsolt** [comment]
Thanks, so I succeeded to do an almost full build, with ffmpeg, and started the server. Now I am trying to find my way through.

A question rose from the beginning: as what user should I run the server?

I've seen the `--user` command line option, but this does not help to decide ;) 
I tend to not start as root, but as a local user also doesn't seem right (how will it write to its webroot?). Was thinking of a `gerbera` user, but don't have this user on the system and don't remember to be mentioned anywhere in the documentation (but I might be wrong).

So I started it as root, and now I am looking at `config.xml`. 

Is it possible to add/import a streaming url from an internet radio station?

**Comment by elmodaddyb** [comment]
@gkzsolt - Great you made progress.

1. Here is how to run Gerbera as a Daemon --> http://docs.gerbera.io/en/latest/daemon.html
  - This should answer your question about runtime user.
2. Yes, you can stream an internet radio URL.
  - Checkout this issue #151 - I am working on ways to import shoutcast, but it includes a workaround if you want to manually add a External URL + `application/octet-stream` which should support a radio URL such as playlist, etc.

**Comment by markusrpi** [comment]
@RedKage Thanks for the instruction to compile Gerbera for the Rasperry Pi 2B on Raspian Stretch. 

But I'm not able to run Gerbera. Here is the output:
```
2018-10-08` 22:11:53    INFO: Gerbera UPnP Server version 1.3.0alpha - http://gerbera.io/
2018-10-08 22:11:53    INFO: ===============================================================================
2018-10-08 22:11:53    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2018-10-08 22:11:53    INFO: Copyright 2016-2018 Gerbera Contributors.
2018-10-08 22:11:53    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2018-10-08 22:11:53    INFO: ===============================================================================
2018-10-08 22:11:53    INFO: Loading configuration from: /home/pi/.config/gerbera/config.xml
2018-10-08 22:11:53    INFO: Checking configuration...
2018-10-08 22:11:53    INFO: Setting filesystem import charset to UTF-8
2018-10-08 22:11:53    INFO: Setting metadata import charset to UTF-8
2018-10-08 22:11:53    INFO: Setting playlist charset to UTF-8
2018-10-08 22:11:53    INFO: Configuration check succeeded.
```
Here it stops working. I have to kill the process...

And here are the last few lines of the debug output:
```
[...]
2018-10-08 22:12:49   DEBUG: [src/config_manager.cc:1978] dumpOptions():  IntOption 83 - 43200
2018-10-08 22:12:49   DEBUG: [src/config_manager.cc:1983] dumpOptions(): BoolOption 84 - false
2018-10-08 22:12:49   DEBUG: [src/config_manager.cc:1978] dumpOptions():  IntOption 85 - 43200
2018-10-08 22:12:49   DEBUG: [src/config_manager.cc:1973] dumpOptions():     Option 86 - 640
2018-10-08 22:12:49   DEBUG: [src/singleton.cc:69] registerSingleton(): registering new singleton... - 1 -> 2
2018-10-08 22:12:49   DEBUG: [src/singleton.cc:69] registerSingleton(): registering new singleton... - 2 -> 3
2018-10-08 22:12:49   DEBUG: [src/server.cc:97] upnp_init(): start
2018-10-08 22:12:49   DEBUG: [src/storage/sqlite3/sqlite3_storage.cc:273] staticThreadProc(): Sqlite3Storage::staticThreadProc - exiting thread
```

Has anybody the same problem? Does anybody know how to solve this?

Thanks
Markus

**Comment by elmodaddyb** [comment]
Hello @markusrpi  - I am a bit stuck, as it looks like the debug statements are relatively normal looking.

Once it is up and running can you confirm if **libupnp** bound to port `49152`?

If everything finished starting, you should see something like:

```
The Web UI can be reached by following this link: http://127.0.0.1:49152/
```

> My guess is that your system is not even getting that far?  

Do you have any more insight?

**Comment by markusrpi** [comment]
Hello @elmodaddyb, thanks für your answer.

I don't see that it is up an running. There appears no note on how to reach the Web UI.
I checked the bound ports: libupnp is not bound to port 49152, it is also not bound to any other port.
Is there a way to check if libupnp has been installed correctly?

You asekd for more insight. What do you want to know?

**Comment by mjbayer** [comment]
Hi all!

I tried to complie latest master based on RedKage and philmoreau's great instructions.

I had to perform followings steps in addition:
- install cmake 3.9 from stretch-backports (cmake 3.8+ is required)
- latest master (b533ee3) did not build with the gcc that is part of debian stretch (gcc-6). Instead of trying to upgrade gcc, I reset master branch to commit 08db874 which compiled fine with gcc-6

**Comment by djstkg** [comment]
> I had the same problem as @peterlopen ( _undefined reference to pthread_*_ ). I was able to fix it by adding `LDFLAGS='-pthread -lpthread'` to to line 14 of "install-pupnp18.sh".
> 
> So the new line is :
> 
> `./bootstrap && ./configure $extraFlags --enable-ipv6 --enable-reuseaddr && make CFLAGS='-D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64' LDFLAGS='-pthread -lpthread' && sudo make install\`

thanks guys, helped me on OrangePi PC2 with Debian Buster Headless

uname -a

`Linux orangepipc2 5.4.28-sunxi64 #20.02.7 SMP Sat Mar 28 17:25:10 CET 2020 aarch64 GNU/Linux`

**Comment by djstkg** [comment]
I am using checkinstall to create packages of all my compilations, easier to keep track and remove if needed.

I would recommend to consider to embed in the installer scripts.

**Comment by b4r0z** [comment]
I was trying to build spdlog as suggested here http://docs.gerbera.io/en/latest/compile.html
on a bananapi (some sort of raspberry clone) but I don't know how to fix this:

```
/usr/bin/ld: /usr/local/lib/libfmt.a(format.cc.o): relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfmt.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
example/CMakeFiles/example.dir/build.make:85: recipe for target 'example/example' failed
make[2]: *** [example/example] Error 1
CMakeFiles/Makefile2:127: recipe for target 'example/CMakeFiles/example.dir/all' failed
make[1]: *** [example/CMakeFiles/example.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

```

any hint please?

**Comment by b4r0z** [comment]
forgive me, now it seems all good.

to build FMT
"To enable compilation with -fPIC use the following CMake command":
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DBUILD_SHARED_LIBS=TRUE ..

to build SPDLOG
cmake -D "SPDLOG_FMT_EXTERNAL:BOOL=true" ..
