### ISSUE TITLE
Compile gerbera on Ubuntu 20.04 LTS Server

### ISSUE THREAD

**Issue by Hospes** [gerbera/gerbera#951]
Hi guys! First of all thank you for this fantastic tool !
Unfortunately i have problem with compiling latest version of gerbera on my ubuntu.
Hope you can help me with it!
```
[  1%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o
/home/hospes/temp/gerbera/src/metadata/ffmpeg_handler.cc: In function ‘std::filesystem::__cxx11::path getThumbnailCacheBasePath(Config&)’:
/home/hospes/temp/gerbera/src/metadata/ffmpeg_handler.cc:270:47: error: ‘CFG_SERVER_EXTOPTS_FFMPEGTHUMBNAILER_CACHE_DIR’ was not declared in this scope
  270 |     if (auto configuredDir = config.getOption(CFG_SERVER_EXTOPTS_FFMPEGTHUMBNAILER_CACHE_DIR);
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/libgerbera.dir/build.make:375: CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/libgerbera.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I've used instruction that described here [doc/compile.rst](https://github.com/gerbera/gerbera/blob/master/doc/compile.rst) for Ubuntu 18.04 LTS

**Comment by ytimenkov** [comment]
Is it latest git or 1.5?
Either it was fixed in git or you can try enabling ffmpeg thumbnailer. Iirc I missed some conditional compilation when l first time fixed crash...

**Comment by Hospes** [comment]
I've cloned current master branch, so might be 1.5. @ytimenkov 
Could you explain me how can I enable ffmpeg thumbnailer? I'm not familar with compilation process at all (sorry). That's my first time :D

**Comment by ytimenkov** [comment]
Install libffmpegthumbnailer-dev and turn this option in cmake.

**Comment by Hospes** [comment]
@ytimenkov thank you for your help! now it works.
But I have another question, after installation I still see on web site `v1.3.5`
Before `sudo make install` i've disabled gerbera.service. So should be fine but the question why i still see old verion name ? is it bug or it's not installed properly ?

**Comment by Hospes** [comment]
Interesting thing is that cli says it's 1.6
```
hospes@hospserver:~/temp/build$ gerbera -v

Gerbera UPnP Server version 1.6.0_git - http://gerbera.io/

===============================================================================
Gerbera is free software, covered by the GNU General Public License version 2

Copyright 2016-2020 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
```

**Comment by ytimenkov** [comment]
🤷‍♂️ make install usually installs into /usr/local, while .service may still use installation from deb. I suggest uninstall distro version first (backing up db and config).
